logging:
  level: INFO

client: ISMT

phases:
  order_allocation:
    enabled: true
    type: partial
    input_source: input
    output_path: intermediate
    csv_inputs:
      so: OID_QTY_RP.csv
      stock: Production_Report.csv

  component_allocation:
    enabled: true
    type: partial
    input_source: intermediate
    output_path: output/
    csv_inputs:
      bom: BOM_Input.csv
      so: OID_QTY_RP.csv
      stock: Production_Report.csv

base_path: D:\000 VDL TESTING WORK\Polars_Alloc_Refactor

schemas:
  so:
    order_id: SO_ID
    fg_id: FG_ID
    order_qty: Order_Qty
    plant: Plant
  stock:
    order_id: order_ID
    fg_id: parenT 
    item_id: Child
    plant: Plant
    stock: Stock
  bom:
    root_parent: Finished_Good
    parent: Parent
    child: Child
    comp_qty: BOM_Ratio_Of_Child
    plant: Plant


# schemas:
#   so:
#     order_id: order_id
#     fg_id: fg_id
#     order_qty: order_qty
#     plant: plant
#   stock:
#     order_id: order_id
#     fg_id: parent
#     item_id: item_id
#     plant: plant
#     stock: stock
#   bom:
#     root_parent: Finished_Good
#     parent: Parent
#     child: Child
#     comp_qty: BOM_Ratio_Of_Child
#     plant: Plant